# Generated by Django 3.2 on 2021-07-28 07:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tea_App', '0002_typesoftea_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Black_tea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tea_picture', models.ImageField(upload_to='black_tea')),
                ('type_name', models.CharField(max_length=100, null=True)),
                ('tea_description', ckeditor.fields.RichTextField()),
                ('first_section', models.BooleanField(default=False)),
                ('second_section', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fermented_tea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tea_picture', models.ImageField(upload_to='fermented_tea')),
                ('type_name', models.CharField(max_length=100, null=True)),
                ('tea_description', ckeditor.fields.RichTextField()),
                ('first_section', models.BooleanField(default=False)),
                ('second_section', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Green_tea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tea_picture', models.ImageField(upload_to='green_tea')),
                ('type_name', models.CharField(max_length=100, null=True)),
                ('tea_description', ckeditor.fields.RichTextField()),
                ('first_section', models.BooleanField(default=False)),
                ('second_section', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Herbal_tea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tea_picture', models.ImageField(upload_to='herbal_tea')),
                ('type_name', models.CharField(max_length=100, null=True)),
                ('tea_description', ckeditor.fields.RichTextField()),
                ('first_section', models.BooleanField(default=False)),
                ('second_section', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matcha_tea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tea_picture', models.ImageField(upload_to='matcha_tea')),
                ('type_name', models.CharField(max_length=100, null=True)),
                ('tea_description', ckeditor.fields.RichTextField()),
                ('first_section', models.BooleanField(default=False)),
                ('second_section', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oolong_tea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tea_picture', models.ImageField(upload_to='oolong_tea')),
                ('type_name', models.CharField(max_length=100, null=True)),
                ('tea_description', ckeditor.fields.RichTextField()),
                ('first_section', models.BooleanField(default=False)),
                ('second_section', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='White_tea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tea_picture', models.ImageField(upload_to='white_tea')),
                ('type_name', models.CharField(max_length=100, null=True)),
                ('tea_description', ckeditor.fields.RichTextField()),
                ('first_section', models.BooleanField(default=False)),
                ('second_section', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
